### ISSUE TITLE
Fix formatting errors

### ISSUE THREAD

**Issue by grep-aarkash** [grep-aarkash/Error-resilience-of-Autonomous-Vehicles#2]
Abdul if you see any, fix and push directly on github. No need to send me a pdf. That is what git is for.

**Comment by abanwer** [comment]
Yeah that's what I am doing. I don't think I have sent you any pdf? Have I missed anything?

**Comment by grep-aarkash** [comment]
I don't know. First complete then I will read.

**Comment by abanwer** [comment]
Done
